<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-89JUI0BR" failures="0" tests="4"
	name="com.ebfs.qa.testcases.HomePageTest" time="0.004" errors="1"
	timestamp="02 Sep 2020 14:42:37 GMT" skipped="3">
	<testcase classname="com.ebfs.qa.testcases.HomePageTest"
		name="setUp" time="0.004">
		<error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.ebfs.qa.base.TestBase.initialization(TestBase.java:43)
at com.ebfs.qa.testcases.HomePageTest.setUp(HomePageTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
		</error>
	</testcase> <!-- setUp -->
	<testcase classname="com.ebfs.qa.testcases.HomePageTest"
		name="verifyHomePageTitleTest" time="0.000">
		<skipped />
	</testcase> <!-- verifyHomePageTitleTest -->
	<testcase classname="com.ebfs.qa.testcases.HomePageTest"
		name="verifyLogoTest" time="0.000">
		<skipped />
	</testcase> <!-- verifyLogoTest -->
	<testcase classname="com.ebfs.qa.testcases.HomePageTest"
		name="verifyContactUsLinkTest" time="0.000">
		<skipped />
	</testcase> <!-- verifyContactUsLinkTest -->
</testsuite> <!-- com.ebfs.qa.testcases.HomePageTest -->
